#!/bin/bash

    docker run -d \
    --name=osd \
    --net=host \
    --restart=always \
    --privileged=true \
    --pid=host \
    -v /home/core/data/ceph/etc/ceph:/etc/ceph \
    -v /home/core/data/ceph/var/lib/ceph:/var/lib/ceph \
    -v /home/core/data/ceph/var/log/ceph:/var/log/ceph \
    -v /dev/:/dev/ \
    -e OSD_FORCE_ZAP=1 \
    -e OSD_DEVICE=/dev/sdb \
    ceph/daemon osd_ceph_disk

