#!/bin/bash
usage()
{
  echo "usage:"
  echo "    drm name1 ... => docker stop name1 && docker stop name1 && .."
  echo "\"name\" is a name of the doker name."
  echo ""
}

if [ $# -gt 0 ];then
  args="$@"
  for arg in $args;do
    docker stop ${arg} && docker rm -f ${arg}
  done
else
  usage
fi


