#!/bin/bash
usage()
{
  echo "usage:"
  echo "    ka something                 => kubectl apply -f something"
  echo "    ka something1 something1 ... => kubectl apply -f something1 -f something ..."
  echo "\"something\" is a name of the config file."
}

if [ $# -gt 0 ];then 
  args="$@"
  for arg in $args;do
    tmp="${tmp} -f ${arg}"
  done
  kubectl apply $tmp
else
  usage
fi


