#!/bin/bash
usage()
{
  echo "usage:"
  echo "    kd something=> kubectl delete something"
  echo "more info,see:\"kubectl delete -h\" or \"kd -h\""
}

if [ $# -ge 1 ]; then
  kubectl delete  $@
else
  usage
fi

