#!/bin/bash
opt="pod,svc,pv,pvc,node,rc,sc,ds,sa"
usage()
{
  echo "usage:"
  echo "    kg something=> kubectl get something"
  echo "\"something\" is the name in \"${opt}\" list."
}

if [ $# == 1 ]; then
  kubectl get  $1
else
  usage
  kubectl get $opt
fi

