#!/bin/bash
usage()
{
  echo "usage:"
  echo "    kg something=> kubectl get something"
  echo "\"something\" is the name in \"kg -h or kubectl get -h\"."
}

if [ $# == 1 ]; then
  kubectl get  $1
else
  usage
  kubectl get all,ep,pv,pvc,node
fi

