apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gce
  namespace: default
  labels: 
    release: "stable"
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce        #GCE 仅支持ReadWriteOnce,ReadOnlyMany,不支持ReadWriteMany
  #persistentVolumeReclaimPolicy: Delete  
  storageClassName: ""
  gcePersistentDisk:
    pdName: gce-disk
    fsType: ext4
