apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gce
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gce-disk
    fsType: ext4
