apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gce
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
