apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #storageClassName: slow
  selector:
    matchLabels:
      release: pv-gce
