apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ceph
  name: ceph
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ceph
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ceph
    spec:
      containers:
      - image: ceph/daemon
        imagePullPolicy: Always
        name: ceph
        env: 
        - name: JOURNAL_DIR
          value: /ceph 
        args: ["OSD"]
        securityContext:
          privileged: true
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: local
          mountPath: /etc/ceph
          subPath: ceph
        - name: local
          mountPath: /var/lib/ceph
          subPath: ceph
        - name: local
          mountPath: /etc/ganesha
          subPath: ceph
      volumes:
      - name: local
        #hostPath: 
        #  path: /home/core/data  
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
