apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ceph
  name: ceph
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ceph
    spec:
      containers:
      - image: ceph/daemon
        imagePullPolicy: Always
        name: ceph
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
