apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  volumes:
  - name: nginx
    hostPath:
      path: /data0/share/nginx
  - name: www
    hostPath:
      path: /data0/share/www
  containers:
  - image: ivories/nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: nginx
      mountPath: /nginx
    - name: www
      mountPath: /www
