apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
  #clusterIP: 10.0.171.239
  #loadBalancerIP: 78.11.24.19
  
