apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nfsd
  name: nfsd
  namespace: default
spec:
  containers:
  - image: gists/nfsd
    imagePullPolicy: Always
    name: nfsd
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
