apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nfsd
  name: nfsd
  namespace: default
spec:
  containers:
  - name: nfsd
    image: itsthenetwork/nfs-server-alpine
    env:
    - name: SHARED_DIRECTORY
      value: /nfsshare
    imagePullPolicy: Always
    securityContext: 
      privileged: true
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: nfsshare
      mountPath: /nfsshare
  volumes:
  - name: nfsshare
    hostPath: 
      path: /home/core/data
#  volumes:
#  - name: nfsshare
#    emptyDir: {}
#  volumes:
#  - name: nfsshare
#    persistentVolumeClaim: 
#      claimName: pvc
