apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nfsc2
  name: nfsc2
  namespace: default
spec:
  containers:
  - name: nfsc2
    image: itsthenetwork/nfs-server-alpine
    env:
    - name: SHARED_DIRECTORY
      value: /nfsshare
    imagePullPolicy: Always
    securityContext: 
      privileged: true
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: nfsshare
      mountPath: /nfsshare
    - name: data
      mountPath: /data
  volumes:
  - name: nfsshare
    emptyDir: {}
  - name: data
    nfs:
      server: 10.31.251.41
      path: /
