apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nfsc
  name: nfsc
  namespace: default
spec:
  containers:
  - name: nfsc
    image: itsthenetwork/nfs-server-alpine
    env:
    - name: SHARED_DIRECTORY
      value: /nfsshare
    imagePullPolicy: Always
    securityContext: 
      privileged: true
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: nfsshare
      mountPath: /nfsshare
    - name: data
      mountPath: /home/core/data
  volumes:
  - name: nfsshare
    emptyDir: {}
  - name: data
    nfs:
      server: 10.43.240.97 #10.31.253.195  #集群IP，集群内跨节点访问 #10.28.3.11 节点IP，节点内跨pod访问
      path: /
