apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsd
  namespace: default
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.51.240.62   #集群IP，集群内跨节点访问; 节点IP，节点内跨pod访问
    path: /
