apiVersion: v1
kind: Service
metadata:
  name: nfss
spec:
  selector:
    app: nfsd
  ports:
  - name: tcp111
    protocol: TCP
    port: 111
    targetPort: 111
    nodePort: 30111    #节点上开放的端口
  - name: tcp2049
    protocol: TCP 
    port: 2049
    targetPort: 2049
    nodePort: 32049    #节点上开放的端口
  - name: udp111
    protocol: UDP
    port: 111
    targetPort: 111
    nodePort: 30111    #节点上开放的端口
  - name: udp2049
    protocol: UDP
    port: 2049
    targetPort: 2049
    nodePort: 32049    #节点上开放的端口
  type: NodePort
