apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      volumes:
      - name: nfsd
        persistentVolumeClaim:
          claimName: nfsd
      containers:
      - image: ivories/mysql:latest
        imagePullPolicy: Always
        name: mysql
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: yellow 
        volumeMounts:
        - name: nfsd
          mountPath: /etc/mysql
          subPath: mysql
        - name: nfsd
          mountPath: /var/lib/mysql
          subPath: mysql/data
        - name: nfsd
          mountPath: /var/log/mysql
          subPath: mysql/log
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
