apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      volumes:
      - name: gce-pvc
        persistentVolumeClaim:
          claimName: gce-pvc
      containers:
      - image: lyclyc88/mysql:latest
        imagePullPolicy: Always
        name: mysql
        #command: ["mysqld"]
        #args: ["--user=root"]
        securityContext:
          privileged: true
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: yellow 
        volumeMounts:
        - name: gce-pvc
          mountPath: /etc/mysql
          subPath: mysql
        - name: gce-pvc
          mountPath: /mysql   #/var/lib/mysql
          subPath: mysql
        - name: nfsd
          mountPath: /var/log/mysql
          subPath: mysql/log
        #resources: 
        #  requests:
        #    memory: "32Mi"
        #    cpu: "50m"
        #  limits:
        #    memory: "96Mi"
        #    cpu: "100m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
