apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  #type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    #nodePort: 30006
    protocol: TCP
    #targetPort: 3306

    
  
