apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php
    spec:
      containers:
      - image: ivories/php:latest
        imagePullPolicy: Always
        name: php
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
