apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
      - name: nfsd
        persistentVolumeClaim:
          claimName: nfsd
      containers:
      - image: ivories/php:latest
        imagePullPolicy: Always
        name: php
        resources: {}
        volumeMounts:
        - name: nfsd
          mountPath: /usr/local/etc/
          subPath: php/conf
#        - name: nfsd
#          mountPath: /etc/php
#          subPath: php/conf
        - name: nfsd
          mountPath: /www
          subPath: www
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
