---
apiVersion: v1
kind: Pod  
metadata:  
  name: redis
  labels:
    name: redis
spec: 
  restartPolicy: Always		#表明该容器一直运行，默认k8s的策略，在此容器退出后，会立即创建一个相同的容器
  containers:
  - name: redis
    image: https://hub.docker.com/r/ivories/redis/  
    ports:
    - containerPort: 6379	#容器开发对外的端口
